### ISSUE TITLE
No options?

### ISSUE THREAD

**Issue by mischugo** [BohemianCoding/sketch-image-compressor#15]
Hello,

i have a bout 24 pages in my document with a lot of artboards ... :-)
I need a really important feature, like:

Only selected artboards (or layers / objects / pages ...) 

Thanks

**Comment by bomberstudios** [comment]
The plugin only compresses whatever you tell Sketch to export, so that functionality is beyond the scope of the plugin: just use the export sheet, or the 'Export Layers' button in the inspector : )
