### ISSUE TITLE
0% compression

### ISSUE THREAD

**Issue by Dooode** [BohemianCoding/sketch-image-compressor#17]
After installing MacOS High Sierra Beta 6 plugin has stopped to compress. It always shows that image is 0.00% off.
<img width="491" alt="issue" src="https://user-images.githubusercontent.com/31205302/29511586-3e3c2e8e-8668-11e7-9a6c-55bd8189f4ee.png">

**Comment by bomberstudios** [comment]
Thanks for the report, will take a look ASAP

**Comment by bomberstudios** [comment]
Apparently this is a bug in CocoaScript (https://github.com/ccgus/CocoaScript/issues/48), I'll see if I can find a workaround.
