### ISSUE TITLE
Plugin not working with Sketch 47.1?

### ISSUE THREAD

**Issue by SebastianSchirmer** [BohemianCoding/sketch-image-compressor#20]
I just installed Sketch 47.1 and somehow the plugin is not working anymore. Tried uninstalling it and reinstalling the most recent version. Not working means, it's not "firing" or "hooking" in when exporting an image from Sketch.

Might it be that the plugin is not compatible with this Sketch version?

**Comment by andrewhag** [comment]
Experiencing the same issue.

**Comment by bomberstudios** [comment]
Thanks for the report, will take a look!

**Comment by bomberstudios** [comment]
Fixed in https://github.com/BohemianCoding/sketch-image-compressor/commit/9649d6df2c9aa17485ff415785ebffbf8b7330c6. Redownload the plugin from https://github.com/BohemianCoding/sketch-image-compressor/commit/9649d6df2c9aa17485ff415785ebffbf8b7330c6 and see if it works for you.

**Comment by SebastianSchirmer** [comment]
Awesome, redownloaded plugin, uninstalled it, reinstalled it, everything works like a charm. Thanks you!!!

**Comment by bomberstudios** [comment]
🙌
