### ISSUE TITLE
No .sketchplugin file

### ISSUE THREAD

**Issue by johanbrook** [BohemianCoding/sketch-image-compressor#5]
README says:

> Double click Sketch Image Compressor.sketchplugin to install the Plugin.

But there's no .sketchplugin file in the repo when downloading the master .zip.

**Comment by bomberstudios** [comment]
My fault, working on it : )

**Comment by bomberstudios** [comment]
Fixed download link : )

**Comment by johanbrook** [comment]
Thanks!
